services:
  comfyui:
    build: .
    container_name: comfyui
    restart: unless-stopped

    ports:
      - "8188:8188"

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]

    volumes:
      - ./comfyui_data:/app/ComfyUI

    environment:
      PYTORCH_CUDA_ALLOC_CONF: "max_split_size_mb:512"
